
const mongoose = require('mongoose');

const EmployeeSchema = mongoose.Schema({
    nom_F: { type: String },
    nom_M: { type: String },
    prenom_E: { type: String },
    prenom_p: { type: String },
    prenom_gp: { type: String },
    prenom_m: { type: String },
    sexe: { type: String },
    nationalite: { type: String },
    date_naiss: { type: String },
    lieu_naiss: { type: String },
    etat_civil: { type: String },
    cin: { type: Number },
    nationale: { type: String },
    type: { type: String },
    acte_naiss: { type: String },
    municipalite: { type: String },
    arrond: { type: String },
    annee: { type: String },
    adr: { type: String },
    appt_num: { type: Number },
    imm_num: { type: Number },
    cite: { type: String },
    localite: { type: String },
    c_p: { type: Number },
    num: { type: Number },
    fax: { type: Number },
    identif: { type: Number },
    id_cnss: { type: String },
    niveau: { type: String },
    diplome: { type: String },
    specialite: { type: String },
    date: { type: String },
    rip: { type: String },
    compte_courrent: { type: String },
    plan: { type: String },
    stage: { type: String },
    periode_contrat: { type: String },
    compte: { type: String },
    gouvernorat: { type: String },
    mat: { type: String },
    num_acte: { type: String },
    date_delivre: { type: String },
    qualite: { type: String },
    pays: { type: String }, 
    envoi_objet: { type: String },
    type_envoi: { type: String },
    envoi_numero: { type: String },
    position_acc: { type: String },
    nature_acc: { type: String },
    lieu: { type: String },
    heure: { type: String },
    date_arret_travail: { type: String },
    periode: { type: String },
    date_rec: { type: String },
    etat: { type: String },
    etat_normal: { type: String },
    residence: { type: String },
    effet_acc: { type: String },
    date_acc: { type: String },
    date_emploi: { type: String },
    activite: { type: String },
    num_employees: { type: String },
    description: { type: String },
    causes: { type: String },
    acc: { type: String },
      
});

module.exports = mongoose.model('employee', EmployeeSchema);